language: node_js
node_js:
  - "8"

install:
  - npm install

git:
  submodules: false

before_script:
  - sudo apt-get install openssl libssl-dev libudev-dev
  - wget -N http://d1h4xl4cr1h0mo.cloudfront.net/v1.10.0/x86_64-unknown-linux-gnu/parity_1.10.0_ubuntu_amd64.deb -P ~/
  - sudo dpkg -i ~/parity_1.10.0_ubuntu_amd64.deb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - git submodule update --init --remote

script:
  - npm test

after_script:
  - cd ./submodules/poanetwork
  - npm run stop-test-setup
